sonar.projectKey=simplonsolutionssenegal_finance4all-frontend
sonar.organization=simplonsolutionssenegal
sonar.projectName=Finance4All Frontend
sonar.projectBaseDir=.

# Code applicatif
sonar.sources=app,components,hooks,lib,types

# Tests
sonar.tests=.
sonar.test.inclusions=**/*.test.{js,jsx,ts,tsx},**/*.spec.{js,jsx,ts,tsx},**/__tests__/**/*

# Exclusions (sources)
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,\
**/*.stories.*,\
**/*.{config,setup}.{js,ts,mjs,cjs},**/jest.config.{js,ts},**/*.setup.{js,ts},\
**/tsconfig*.json,**/package*.json,**/components.json,\
**/__tests__/**,**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx,\
**/components/ui/**

# Exclusions (couverture)
sonar.coverage.exclusions=**/*.stories.*,**/*.{config,setup}.{js,ts,mjs,cjs},\
**/jest.config.{js,ts},**/jest.setup.{js,ts},**/tsconfig*.json,**/package*.json,**/components.json,\
**/*.test.{js,jsx,ts,tsx},**/*.spec.{js,jsx,ts,tsx},**/__tests__/**/*,**/tests/**/*,\
**/components/ui/**

# Rapports de couverture générés par Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

# Déco PR GitHub
sonar.pullrequest.github.repository=simplonsolutionssenegal/Finance4All
sonar.pullrequest.provider=github