sonar.organization=simplonsolutionssenegal
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

# Déco PR GitHub
sonar.pullrequest.github.repository=simplonsolutionssenegal/Finance4All
sonar.pullrequest.provider=github
