sonar.projectKey=simplonsolutionssenegal_finance4all-backend
sonar.organization=simplonsolutionssenegal
sonar.projectName=Finance4All Backend
sonar.projectBaseDir=.

# Sources
sonar.sources=src

# Tests
sonar.tests=.
sonar.test.inclusions=**/*.test.{js,ts},**/*.spec.{js,ts}

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,\
**/*.{config,setup}.{js,ts,mjs,cjs},**/jest.config.{js,ts},**/tsconfig*.json,**/package*.json

# Couverture
sonar.coverage.exclusions=**/*.{config,setup}.{js,ts,mjs,cjs},**/jest.config.{js,ts},\
**/tsconfig*.json,**/package*.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

# Déco PR GitHub
sonar.pullrequest.github.repository=simplonsolutionssenegal/Finance4All
sonar.pullrequest.provider=github