export const InstitutionType = Object.freeze({
  ETABLISSEMENT_MONNAIE_ELECTRONIQUE: 'ETABLISSEMENT_MONNAIE_ELECTRONIQUE',
  PORTEFEUILLE_NUMERIQUE: 'PORTEFEUILLE_NUMERIQUE',
  SERVICE_PAIEMENT_ELECTRONIQUE: 'SERVICE_PAIEMENT_ELECTRONIQUE',
  BANQUE_NUMERIQUE: 'BANQUE_NUMERIQUE',
  SERVICE_FINANCIER_DECENTRALISE: 'SERVICE_FINANCIER_DECENTRALISE',
  SERVICE_FINANCEMENT_PARTICIPATIF: 'SERVICE_FINANCEMENT_PARTICIPATIF',
  SERVICE_INVESTISSEMENT: 'SERVICE_INVESTISSEMENT',
  SERVICE_GESTION_FINANCIERE: 'SERVICE_GESTION_FINANCIERE',
  SERVICE_ASSURANCE_NUMERIQUE: 'SERVICE_ASSURANCE_NUMERIQUE',
});

export type InstitutionTypeEnum = (typeof InstitutionType)[keyof typeof InstitutionType];
