-- CreateEnum
CREATE TYPE "public"."InstitutionType" AS ENUM ('ETABLISSEMENT_MONNAIE_ELECTRONIQUE', 'PORTEFEUILLE_NUMERIQUE', 'SERVICE_PAIEMENT_ELECTRONIQUE', 'BANQUE_NUMERIQUE', 'SERVICE_FINANCIER_DECENTRALISE', 'SERVICE_FINANCEMENT_PARTICIPATIF', 'SERVICE_INVESTISSEMENT', 'SERVICE_GESTION_FINANCIERE', 'SERVICE_ASSURANCE_NUMERIQUE');

-- CreateEnum
CREATE TYPE "public"."Country" AS ENUM ('SENEGAL', 'CAMEROUN');

-- AlterTable
ALTER TABLE "public"."Institution" ADD COLUMN     "pays" "public"."Country" NOT NULL DEFAULT 'SENEGAL',
ADD COLUMN     "type" "public"."InstitutionType" NOT NULL DEFAULT 'ETABLISSEMENT_MONNAIE_ELECTRONIQUE';
